version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Hello World Sep 28"
    
workflows:
  test-workflow:
    jobs:
      - test:
          name: "test stg"
      - test:
          name: "test dev"
      - test:
          name: "test prod"
      
